import { Item } from "@/types";

export const CardData: Item[] = [
    {
        id:1,
        slug:"mens-Lhotse-1",
        label:"Men’s Lhotse Reversible Hoodie",
        category:"black-friday-sale",
        isNew:true,
        img:[
            "/catwomen.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#98C8DC",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:2,
        slug:"mens-Lhotse-2",
        label:"Women’s Lhotse Reversible Jacket",
        category:"womens",
        isNew:true,
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#F5EFEA",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {  
        id:3,
        slug:"mens-Lhotse-3",
        label:"Men’s Lhotse Reversible Hoodie",
        category:"men's",
        img:[
            "/catmen.jpg",
            "/catkids.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#FF9900",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:4,
        slug:"mens-Lhotse-4",
        label:"Women’s Lhotse Reversible Jacket",
        category:"kid's",
        img:[
            "/catwomenshoes.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#B177DB",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:5,
        slug:"mens-Lhotse-5",
        label:"Men’sss Lhotse Reversible Hoodie",
        category:"footwarear",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#635BFF",
            "#999",
            "#e4e4",
        ]
    },
    {
        id:6,
        slug:"mens-Lhotse-6",
        label:"Women’s Lhotse Reversible Jacket",
        category:"bags-and-gear",
        img:[
            "/catwomenshoes.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#C22BAF",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:70,
        slug:"mens-Lhotse-6",
        label:"Women’s Lhotse Reversible Jacket",
        category:"bags-and-gear",
        img:[
            "/catwomenshoes.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#EC2426",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:7,
        slug:"mens-Lhotse-7",
        label:"Men’s Lhotse Reversible Hoodie",
        category:"renewed",
        isNew:true,
        img:[
            "/catkids.jpg",
            "/catwomenshoes.jpg",
            "/catmen.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#E7F9FE",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:8,
        slug:"mens-Lhotse-8",
        label:"Women’s Lhotse Reversible Jacket",
        category:"women's",
        img:[
            "/catmen.jpg",
            "/catkids.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#FB0719",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:9,
        slug:"mens-Lhotse-9",
        label:"Men’s Lhotse Reversible Hoodie",
        category:"men's",
        img:[
            "/catkids.jpg",
            "/catwomen.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#FDECF0",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:10,
        slug:"mens-Lhotse-10",
        label:"Women’s Lhotse Reversible Jacket",
        category:"black-friday-sale",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#1A814A",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:11,
        slug:"mens-Lhotse-11",
        label:"Men’s Lhotse Reversible Hoodie",
        category:"kid's",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#65B4D3",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:12,
        slug:"mens-Lhotse-12",
        label:"Women’s Lhotse Reversible Jacket",
        category:"footwear",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#E94E22",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:13,
        slug:"mens-Lhotse-13",
        label:"Women’s Lhotse Reversible Jacket",
        category:"bags-and-gear",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#FF9900",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:14,
        slug:"mens-Lhotse-1",
        label:"Men’s Lhotse Reversible Hoodie",
        category:"black-friday-sale",
        isNew:true,
        img:[
            "/catwomen.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#98C8DC",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:15,
        slug:"mens-Lhotse-9",
        label:"Men’s Lhotse Reversible Hoodie",
        category:"men's",
        img:[
            "/catkids.jpg",
            "/catwomen.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#FDECF0",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
]