export const  CardData = [
    {
        id:1,
        slug:"mens-Lhotse-1",
        label:"Men’s Lhotse Reversible Hoodie",
        link:"/mens-scale",
        img:[
            "/catwomen.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:2,
        slug:"mens-Lhotse-2",
        label:"Women’s Lhotse Reversible Jacket",
        link:"/womens-scale",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {  
        id:3,
        slug:"mens-Lhotse-3",
        label:"Men’s Lhotse Reversible Hoodie",
        link:"/mens-scale",
        img:[
            "/catmen.jpg",
            "/catkids.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:4,
        slug:"mens-Lhotse-4",
        label:"Women’s Lhotse Reversible Jacket",
        link:"/womens-scale",
        img:[
            "/catwomenshoes.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:5,
        slug:"mens-Lhotse-5",
        label:"Men’sss Lhotse Reversible Hoodie",
        link:"/mens-scale",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:6,
        slug:"mens-Lhotse-6",
        label:"Women’s Lhotse Reversible Jacket",
        link:"/womens-scale",
        img:[
            "/catwomenshoes.jpg",
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:7,
        slug:"mens-Lhotse-7",
        label:"Men’s Lhotse Reversible Hoodie",
        link:"/mens-scale",
        img:[
            "/catkids.jpg",
            "/catwomenshoes.jpg",
            "/catmen.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:8,
        slug:"mens-Lhotse-8",
        label:"Women’s Lhotse Reversible Jacket",
        link:"/womens-scale",
        img:[
            "/catmen.jpg",
            "/catkids.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:9,
        slug:"mens-Lhotse-9",
        label:"Men’s Lhotse Reversible Hoodie",
        link:"/mens-scale",
        img:[
            "/catkids.jpg",
            "/catwomen.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:10,
        slug:"mens-Lhotse-10",
        label:"Women’s Lhotse Reversible Jacket",
        link:"/womens-scale",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:11,
        slug:"mens-Lhotse-11",
        label:"Men’s Lhotse Reversible Hoodie",
        link:"/mens-scale",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg"
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
    {
        id:12,
        slug:"mens-Lhotse-12",
        label:"Women’s Lhotse Reversible Jacket",
        link:"/womens-scale",
        img:[
            "/catkids.jpg",
            "/catmen.jpg",
            "/catwomenshoes.jpg",
            "/catwomen.jpg",
        ],
        prevPrice:"280.00",
        currPrice:"196.00",
        color:[
            "#000",
            "#999",
            "#e4e4",
            "#80e3"
        ]
    },
]